# ApkDownloader Default Configuration
# This file contains default settings that can be overridden by CLI arguments

# API Settings
api:
  url: "https://androzoo.uni.lu/api/download"
  # API_KEY should be set in .env file for security

# Directory Settings
directories:
  download: "./downloads"
  cache: "./_cache"
  logs: "./logs"

# Default Sample Selection
samples:
  malware_threshold: 4
  default_cleanware_count: 1000
  default_malware_count: 500

# Default Date Range
date_range:
  # These are just defaults - usually overridden by CLI
  start: "2022-04-01 00:00:00"
  end: "2024-12-01 00:00:00"

# Performance Settings
performance:
  concurrent_downloads: 12

# Options
options:
  verify_existing_file_hash: false
  random_seed: 42  # null means random, set number for reproducibility